---
apiVersion: k3d.io/v1alpha4
kind: Simple
# name: k3s-default-configfile
servers: 1
agents: 3
image: docker.io/rancher/k3s:v1.22.7-k3s1

ports:
  - port: 8080:80 # same as `--port '8080:80@loadbalancer'`
    nodeFilters:
      - loadbalancer

# options:
#   k3d: # k3d runtime settings
#     wait: true # wait for cluster to be usable before returining; same as `--wait` (default: true)
#     timeout: "60s" # wait timeout before aborting; same as `--timeout 60s`
#     disableLoadbalancer: false # same as `--no-lb`
#     disableImageVolume: false # same as `--no-image-volume`
#     disableRollback: false # same as `--no-Rollback`
#     loadbalancer:
#       configOverrides:
#         - settings.workerConnections=2048
